// Assembles the folder that gets deployed to Vercel:
//
//   /           guest download page (web/)
//   /booth/     the booth itself, for tablets that can't install the APK
//
// The booth key is deliberately NOT written into any file here. The operator
// opens /booth/?k=<key> once; the page keeps the key in that tablet's own
// storage and strips it from the address bar.

import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const out = new URL("dist/web/", root);
const path = (url) => fileURLToPath(url);

await rm(path(out), { recursive: true, force: true });
await mkdir(path(out), { recursive: true });

// guest page, as it already is
await cp(path(new URL("web/", root)), path(out), {
  recursive: true,
  filter: (src) => !/[\\/](\.vercel|\.env\.local|\.gitignore)$/.test(src),
});

// booth app, minus the config the APK build writes
await cp(path(new URL("app/www/", root)), path(new URL("booth/", out)), {
  recursive: true,
  filter: (src) => !/[\\/]config\.js$/.test(src),
});

// web/config.js is plain JS, not JSON, so it is run rather than parsed.
const guestSource = await readFile(path(new URL("web/config.js", root)), "utf8");
const guest = new Function(`const window = {}; ${guestSource}; return window.GUEST_CONFIG;`)();

const boothConfig = `// Generated by dev/build-web.mjs — do not edit by hand.
//
// Open /booth/?k=<부스 키> once on the tablet. The key is kept in this
// browser's storage from then on and removed from the address bar, so the
// plain /booth/ address on its own is useless to anyone who finds it.
(() => {
  const KEY_STORE = "booth-key";
  const url = new URL(location.href);
  const fromUrl = url.searchParams.get("k");
  let key = "";

  try {
    if (fromUrl) {
      localStorage.setItem(KEY_STORE, fromUrl);
      url.searchParams.delete("k");
      history.replaceState(null, "", url.pathname + url.hash);
    }
    key = fromUrl || localStorage.getItem(KEY_STORE) || "";
  } catch {
    key = fromUrl || ""; // private browsing: works for this visit only
  }

  window.BOOTH_CONFIG = {
    functionsUrl: ${JSON.stringify(guest.functionsUrl)},
    publishableKey: ${JSON.stringify(guest.publishableKey)},
    // The guest page ships alongside the booth, whatever host this lands on.
    guestPageUrl: new URL("/s", location.origin).href,
    eventName: ${JSON.stringify(guest.eventName ?? "")},
    boothKey: key,
    version: "웹",
  };

  if (key) return;
  addEventListener("DOMContentLoaded", () => {
    document.body.innerHTML =
      '<main style="font:500 18px/1.6 system-ui;max-width:32rem;margin:18vh auto;padding:0 24px;color:#000">' +
      '<h1 style="font-size:28px;letter-spacing:-.02em;margin:0 0 12px">부스 키가 필요해요</h1>' +
      '<p style="color:#5f5f5c;margin:0">주소 끝에 <code>?k=부스키</code> 를 붙여서 한 번만 열어주세요. ' +
      '그 뒤로는 이 태블릿에서 주소만으로 열립니다.</p></main>';
  });
})();
`;

await writeFile(path(new URL("booth/config.js", out)), boothConfig, "utf8");

const vercel = JSON.parse(await readFile(path(new URL("web/vercel.json", root)), "utf8"));
vercel.headers.push({
  source: "/booth/(.*)",
  headers: [{ key: "Cache-Control", value: "no-cache" }],
});
await writeFile(path(new URL("vercel.json", out)), JSON.stringify(vercel, null, 2), "utf8");

console.log(`built ${path(out)}`);
